### ISSUE TITLE
Manual download doesn't work

### ISSUE THREAD

**Issue by ghost** [flathub/de.uni_heidelberg.zah.GaiaSky#1]
After first start, when I click on manual download on data download screen, nothing happens.

**Comment by BryanQuigley** [comment]
Interesting, that just opens a browser to https://gaia.ari.uni-heidelberg.de/gaiasky/files/autodownload/ so you can download using another download manager, etc.  Found a bunch of other links that also don't work.

Tried using gedit as example flatpak, but their about links hilariously load html in gedit.. /me needs to read more into how this is supposed to work.

**Comment by BryanQuigley** [comment]
This is is fixed in 3.2.0 - (likely downloadable in next few hours to EOD)
