### ISSUE TITLE
Duplicate screenshots

### ISSUE THREAD

**Issue by ls-1N** [flathub/de.uni_heidelberg.zah.GaiaSky#36]
On Flathub the [app page](https://flathub.org/apps/de.uni_heidelberg.zah.GaiaSky) features duplicate screenshots.

**Comment by BryanQuigley** [comment]
I've confirmed the website shows the same number of images as we have in: https://github.com/flathub/de.uni_heidelberg.zah.GaiaSky/blob/master/de.uni_heidelberg.zah.GaiaSky.metainfo.xml

But in that file they are not duplicated.  I couldn't find any other apps that have this many images - but maybe it's a bug somewhere in the build process?

**Comment by BryanQuigley** [comment]
opened https://github.com/flathub/flathub/issues/4638 as I'm not really how to debug it next.

**Comment by BryanQuigley** [comment]
This was fixed by flathub devs.  Thanks to them for fixing it and thanks for reporting
